#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-Atom-Syndication
version:      0.091
version_from: lib/XML/Atom/Syndication.pm
installdirs:  site
requires:
    XML::Parser:                   0
    XML::Parser::Style::Elemental: 0
    LWP::Simple:                   0
    Class::XPath:                  1.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
